export const incomeSocketCommands = {
    LEAVE_ROOM_COMMAND: 'LEAVE_ROOM',
    CONNECT_COMMAND: 'CONNECT',
    MESSAGE_COMMAND: 'MESSAGE'
};
export const outputSocketCommands = {
    NEW_MESSAGE_COMMAND: 'NEW_MESSAGE',
    CHAT_CONNECTED_COMMAND: 'CHAT_CONNECTED',
    COMPANION_CONNECTED_COMMAND: 'COMPANION_CONNECTED',
    ROOM_CREATED_COMMAND: 'ROOM_CREATED',
    CHAT_CLOSED_COMMAND: 'CHAT_CLOSED'
};
