export const SOCKET_ACTIONS = {
    CHAT_CONNECTED: "CHAT_CONNECTED",
    COMPANION_CONNECTED: "COMPANION_CONNECTED",
    NEW_MESSAGE: "NEW_MESSAGE",
    CHAT_CLOSED: "CHAT_CLOSED",
    LEAVE_ROOM: "LEAVE_ROOM",
    CONNECT: "CONNECT",
    MESSAGE: "MESSAGE"
};